# Generated by Django 5.2.8 on 2025-12-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_manager",
            field=models.BooleanField(
                default=False, help_text="Отметьте, если пользователь является менеджером", verbose_name="Менеджер"
            ),
        ),
    ]
