# Generated by Django 5.2.8 on 2025-12-02 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='date_start',
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 7, 33, 44, 354172, tzinfo=datetime.timezone.utc), verbose_name='Дата и время окончания отправки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 7, 33, 51, 536254, tzinfo=datetime.timezone.utc), verbose_name='Дата и время начала отправки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('finished', 'Завершена')], default='created', max_length=20),
        ),
    ]
