# Generated by Django 5.2.8 on 2025-11-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылок'},
        ),
    ]
