# Generated by Django 5.2.8 on 2025-12-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_all_messages", "может просматривать все сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(verbose_name="Тело сообщения"),
        ),
    ]
