# Generated by Django 5.2.8 on 2025-12-05 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglog",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing_logs",
                to="mailing.client",
            ),
        ),
    ]
